language: python

sudo: false

python:
  - "2.7"

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy atlas scipy pandas matplotlib libnetcdf netcdf4 pytest
  - pip install -r test-requirements.txt
  - pip install codecov pytest-cov
  - python setup.py install

#install:
#  - "pip install tox"
#  - "pip install coveralls"

# script: tox -e $TOX_ENV

script: py.test tests

#script:
#  - py.test --cov --cov-report=term-missing -vv
#
#after_success:
#  - codecov
